version: '3'
services:
  ph:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 1111
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_DB: ph
      JWT_SECRET_KEY: JWTSecretKey
      JWT_EXPIRED_MINUTE: 10
  mysql:
    image: mysql:5.7.31
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: "1111"
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --innodb-use-native-aio=0
